/** Shared typography for reading pages (articles + course overviews) — Notion/Medium feel */
export const proseCss = {
  fontSize: '1.0625rem',
  lineHeight: '1.9',
  color: { base: 'gray.800', _dark: 'gray.100' },
  '& h1': {
    fontSize: '1.9em',
    fontWeight: 'bold',
    mb: 4,
    mt: 8,
    lineHeight: 1.3,
    letterSpacing: '-0.01em',
  },
  '& h2': {
    fontSize: '1.45em',
    fontWeight: 'bold',
    mb: 3,
    mt: 10,
    pb: 2,
    lineHeight: 1.35,
    borderBottomWidth: '1px',
    borderBottomColor: { base: 'gray.200', _dark: 'whiteAlpha.200' },
  },
  '& h3': {
    fontSize: '1.22em',
    fontWeight: 'bold',
    mb: 3,
    mt: 7,
    lineHeight: 1.4,
  },
  '& h4': { fontWeight: 'bold', mb: 2, mt: 5 },
  '& p': { mb: 5 },
  '& img': {
    display: 'block',
    mx: 'auto',
    maxWidth: '100%',
    borderRadius: 'lg',
    my: 6,
  },
  '& ul, & ol': { mb: 5, pl: 6 },
  '& ul': { listStyleType: 'disc' },
  '& ol': { listStyleType: 'decimal' },
  '& li': { mb: 2.5, lineHeight: 1.85 },
  '& li::marker': { color: 'teal.500' },
  '& a': {
    color: 'teal.500',
    fontWeight: 'medium',
    textDecoration: 'underline',
    textDecorationThickness: '1px',
    textUnderlineOffset: '3px',
  },
  '& strong, & b': { fontWeight: 'bold' },
  '& pre': {
    bg: { base: 'gray.50', _dark: '#1b1b1f' },
    border: '1px solid',
    borderColor: { base: 'gray.200', _dark: 'whiteAlpha.200' },
    p: 5,
    borderRadius: 'lg',
    overflowX: 'auto',
    mb: 5,
    mt: 2,
    fontSize: '0.85em',
    lineHeight: 1.75,
  },
  '& :not(pre) > code': {
    bg: { base: 'gray.100', _dark: 'whiteAlpha.200' },
    px: 1.5,
    py: 0.5,
    borderRadius: 'sm',
    fontSize: '0.875em',
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, monospace',
    color: { base: 'gray.800', _dark: 'gray.100' },
  },
  '& pre code': { bg: 'transparent', p: 0, fontSize: '1em' },
  '& blockquote': {
    borderLeft: '3px solid',
    borderColor: 'teal.500',
    pl: 5,
    pr: 2,
    py: 1,
    mb: 5,
    fontStyle: 'normal',
    color: { base: 'gray.600', _dark: 'whiteAlpha.800' },
  },
  '& blockquote p': { mb: 2 },
  '& hr': {
    my: 9,
    borderColor: { base: 'gray.200', _dark: 'whiteAlpha.200' },
  },
  '& table': {
    width: '100%',
    mb: 5,
    borderCollapse: 'collapse',
    fontSize: '0.92em',
    display: 'table',
  },
  '& th': {
    border: '1px solid',
    borderColor: { base: 'gray.200', _dark: 'whiteAlpha.300' },
    bg: { base: 'gray.50', _dark: 'whiteAlpha.100' },
    px: 4,
    py: 2,
    textAlign: 'left',
    fontWeight: 'bold',
  },
  '& td': {
    border: '1px solid',
    borderColor: { base: 'gray.200', _dark: 'whiteAlpha.300' },
    px: 4,
    py: 2,
  },
  '& tr:hover': {
    bg: { base: 'gray.50', _dark: 'whiteAlpha.100' },
  },
}
